api/urls.py
from rest_framework.urlpatterns import format_suffix_patterns
from django.urls import re_path
from . import views
api_urlpatterns = format_suffix_patterns([
    re_path(r'^api/$', views.api_root,name='api-index'),
    re_path(r'^api/article-list/$', views.ArticleList.as_view(),name='article-list'),
    re_path(r'^api/article/(?P<pk>[0-9]+)/$', views.ArticleDetail.as_view(),name='article-detail'),
])

blog/urls.py
import notifications.urls
from api.urls import api_urlpatterns
from django.urls import re_path,path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^index/', include(('main_article.urls','main_article'))),
    re_path(r'^accounts/', include('allauth.urls')),
    #url(r'^.*', include('main_article.urls')),#与ckeditor图片预览冲突
    re_path(r'^', include('main_article.urls')), 
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r'', include('easy_comment.urls')),
    re_path(r'^notifications/', include(('notifications.urls','notifications'))),
    re_path(r'^guestbook/',include(('guestbook.urls','guestbook'))),
    re_path(r'^', include('extra_apps.django_private_chat.urls')),
    path('api-auth/', include('rest_framework.urls')),
    ] 

urlpatterns += api_urlpatterns
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

easy_comment/urls.py
from django.urls import re_path
from . import views

app_name = 'easy_comment'
urlpatterns = [
    re_path(r'^post/(?P<id>[0-9]+)/submit-comment/$', views.submit_comment, name='submit_comment'),
    re_path(r'^comment/like/$', views.like, name='like'),
]

easy_comment/models.py
from django.db import models
from django.conf import settings
from mptt.models import TreeForeignKey, MPTTModel
from extra_apps.ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
# Create your models here.

class Comment(MPTTModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True,on_delete=models.CASCADE)
    user_name = models.CharField(max_length=50, blank=True, null=True)
    post = models.ForeignKey(settings.COMMENT_ENTRY_MODEL, verbose_name='文章',on_delete=models.CASCADE)
    parent = TreeForeignKey('self', blank=True, null=True, verbose_name='父级评论',on_delete=models.CASCADE)
    content = RichTextUploadingField(verbose_name='评论', config_name='comment')
    submit_date = models.DateTimeField(auto_now_add=True, db_index=True,verbose_name='提交时间')

    class Meta:
        verbose_name='文章留言'
        verbose_name_plural='文章留言'    
    class MPTTMeta:
        order_insertion_by = ['-submit_date']


    def __str__(self):
        if self.parent is not None:
            return '%s 回复 (%s)' % (self.user_name, self.parent.user_name)
        return '%s 评论文章(%s)' % (self.user_name, self.post.title)
    def get_absolute_url(self):
        return reverse('main_article:articleRead',args=[self.post.id])

class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment,on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    class Meta:
        verbose_name='留言点赞'
        verbose_name_plural=verbose_name
    def __str__(self):
        if self.status:
            return '%s 赞了( %s)的评论' % (self.user.username, self.comment.user_name)
        return '%s 踩了( %s)的评论' % (self.user.username, self.comment.user_name)

easy_comment/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    honeypot = forms.CharField(required=False,
                               label='If you enter anything in this field, you comment will be treated as spam!')
    class Meta:
        model = Comment
        fields = ('content', 'parent', 'post')

    # 验证honeypot字段，如果有输入，则是垃圾评论
    def clean_honeypot(self):
        value = self.cleaned_data['honeypot']
        if value:
            return forms.ValidationError(self.fields['honeypot'].error_message)
        return value

easy_comment/views.py
from easy_comment.forms import CommentForm
from easy_comment.models import Comment, Like
from django.http import JsonResponse
from django.views.decorators.http import require_POST
#from django.shortcuts import render,redirect
from . import handlers
from activity_stream.utils import create_action
# Create your views here.

@require_POST
def submit_comment(request, id):
    form = CommentForm(data=request.POST)
    # print(request.POST)
    if form.is_valid():
        # print('success')
        new_comment = form.save(commit=False)
        new_comment.user = request.user
        new_comment.user_name =  request.user.profile.nickname if request.user.profile.nickname else request.user
        #print(new_comment.user_name)
        new_comment.save()
        #action create
        create_action(request.user, '发表了评论', new_comment)
        location = "#c" + str(new_comment.id)
        return JsonResponse({'msg':'success!', 'new_comment':location})
    return JsonResponse({'msg':'评论出错!'})
    

@require_POST
def like(request):
    comment_id = request.POST.get('id')
    action = request.POST.get('action')
    if comment_id and action:
        try:
            comment = Comment.objects.get(id=comment_id)
            obj, created = Like.objects.get_or_create(user = request.user, comment = comment)
            if action == 'like':
                if not created:
                    obj.status = True
                    obj.save()
                    #print(obj)
                    create_action(request.user, '点赞了评论', obj)
            if action == 'cancel-like' or action == 'cancel-dislike':
                obj.delete()
            if action == 'dislike':
                obj.status = False
                obj.save()
            return JsonResponse({'msg':'OK'})
        except Comment.DoesNotExist:
            return JsonResponse({"msg":"KO"})
    return JsonResponse({"msg":"KO"})

easy_comment/templates/easy_comment/comment_form.html
{% load staticfiles %}
{% load comment_tags %}

{% generate_form_for post as form %}
<div class="container-fluid" id="cmt-form">
{% if request.user.is_authenticated %}
    
        <a class="comment-avatar">
            <img class="img-rounded" src="{{ user.profile.avatar.url }}">
        </a>
        <span><strong>
            {% if request.user.profile.nickname %}
            {{request.user.profile.nickname}}
            {% else %}
            {{request.user.username}}
            {% endif %}
        </strong></span>
        <span class="glyphicon glyphicon-edit"></span>
        <span id="reply-to" style="display:none;">回复：<a class="reply-to-name" href="javascript:void(0);"></a></span>
    
    <form class="comment-form" method="post" action="{% url 'easy_comment:submit_comment' post.id %}">
        {% csrf_token %}
        {% for field in form %}
        {{ field }}
        {{ field.errors }}
        {% endfor %}
        <button style="margin-top:10px;" class="btn btn-primary pull-right" type="submit">提交评论</button>
        
    </form>
    <button class="btn btn-danger pull-right" id="cancel-reply" style="display: none">取消回复</button>
{% else %}
    <div class="jumbotron">
        <h3 class="text-center"><a class="red"href="{% url 'account_login' %}?next={{ request.get_full_path }}"><b>登录</b></a>后参与评论</h3>
    </div>
{% endif %}
</div>

<!-- 在非admin后台的地方使用django-ckeditor，需要引入这两个js -->
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<script src="http://cdn.bootcss.com/jquery/2.1.4/jquery.min.js"></script>
<script>
    $(window).load(function () {
        if (!$(".comment-reply").hasClass('no-login') && $(".comment-reply").length != 0){
            //console.log($(".comment-form")[0])
            $(".comment-form")[0].reset();
        }
        if (sessionStorage.getItem('reply')){
            sessionStorage.removeItem('reply');
        }

        // if true,说明是提交评论后刷新的页面，将位置跳到新评论处
        if (sessionStorage.getItem('anchor')){
            var top = $(sessionStorage.getItem('new_comment')).offset().top;
            $('body,html').animate({scrollTop:top}, 50);
            window.location.hash = sessionStorage.getItem('new_comment');
            sessionStorage.removeItem('anchor');
        }
    });
    $(document).ready(function () {
        $(".comment-content img").removeAttr('style');
        // 点击取消回复按钮，按钮消失，同时抹除sessionStorage里记录的reply
        $("#cancel-reply").click(function () {
            sessionStorage.removeItem('reply');
            document.getElementById('cancel-reply').style.display = 'none';
            document.getElementById('reply-to').style.display = 'none';
        });

        // 点击评论里的回复，页面定位到评论框，同时取消回复按钮出现
        $(".comment-reply").click(function () {
            if ($(this).hasClass('no-login')){
                alert('登陆后才能回复');
                return false;
            }
            var pid = $(this).attr('ID').replace('a-', '');
            sessionStorage.setItem('reply', true);
            sessionStorage.setItem('pid', pid);
            document.getElementById('cancel-reply').style.display = '';
            $(".reply-to-name").text($(this).data('name'));
            document.getElementById('reply-to').style.display = '';
        });

        // 提交评论，发送ajax post
        $(".comment-form").submit(function (e) {
            e.preventDefault();
            // 如果是机器发的垃圾信息，表单的所有字段都会填写
            if ($("#id_honeypot").val().length > 0){
                alert("spam!");
                return false;
            }
            content = CKEDITOR.instances.id_content.getData();
            var list = content.replace(/<.*?>/ig,"").replace(/&nbsp;/ig, "").replace(/\s/g, "");
            if (list.length == 0){
                alert("评论不能为空！！");
                window.location.reload();
                return false;
            }
            $.ajaxSetup({
                data: {csrfmiddlewaretoken: '{{ csrf_token }}' }
            });
            pid = $('#id_parent option:selected').val();
            if (sessionStorage.getItem('reply')){
                pid = sessionStorage.getItem('pid');
                sessionStorage.removeItem('reply');
            }
            $.ajax({
                type:'post',
                url:"{% url 'easy_comment:submit_comment' post.id %}",
                data:{
                    'honeypot':$("#id_honeypot").val(),
                    'content':content,
                    'parent':pid,
                    'post':$('#id_post option:selected').val()
                },
                dataType:'json',
                // 提交成功后，根据返回数据，把新评论的id保存在sessionStorage中，然后刷新页面
                success:function (json) {
                    sessionStorage.setItem('anchor', true);
                    sessionStorage.setItem('new_comment', json.new_comment);
                    window.location.reload();
                },
                error:function (json) {
                    alert(json.msg);
                }
            });
        });
        $("a.like").click(function (e) {
            e.preventDefault();
            if ($(this).hasClass('no-login')){
                alert('请在登陆后执行该操作');
                return false;
            }
            var x = $(this).data('id');
            var action = $(this).data('action');
            var like_obj = $("#like-" + x);
            var dislike_obj = $("#dislike-" + x);
            var like_num = parseInt($(like_obj).find("span.like-total").text());
            var dislike_num = parseInt($(dislike_obj).find("span.dislike-total").text());
            if (action == 'like'){
                $(like_obj).find("span.like-total").text(like_num + 1);
                $(like_obj).find("span.glyphicon").addClass('red-finger');
                $(like_obj).data('action', 'cancel-like');
                if ($(dislike_obj).data('action') == 'cancel-dislike'){
                    $(dislike_obj).find("span.dislike-total").text(dislike_num + 1);
                    $(dislike_obj).find("span.glyphicon").removeClass('red-finger');
                    $(dislike_obj).data('action', 'dislike');
                }
            }
            if (action == 'cancel-like'){
                $(like_obj).find("span.like-total").text(like_num - 1);
                $(like_obj).find("span.glyphicon").removeClass('red-finger');
                $(like_obj).data('action', 'like');
            }
            if (action == 'dislike'){
                $(dislike_obj).find("span.dislike-total").text(dislike_num - 1);
                $(dislike_obj).find("span.glyphicon").addClass('red-finger');
                $(dislike_obj).data('action', 'cancel-dislike');
                if ($(like_obj).data('action') == 'cancel-like'){
                    $(like_obj).find("span.like-total").text(like_num - 1);
                    $(like_obj).find("span.glyphicon").removeClass('red-finger');
                    $(like_obj).data('action', 'like');
                }
            }
            if (action == 'cancel-dislike'){
                $(dislike_obj).find("span.dislike-total").text(dislike_num + 1);
                $(dislike_obj).find("span.glyphicon").removeClass('red-finger');
                $(dislike_obj).data('action', 'dislike');
            }
            $.ajaxSetup({
                data: {csrfmiddlewaretoken: '{{ csrf_token }}' }
             });
            $.post(
                '{% url 'easy_comment:like' %}',
                {
                    id:x,
                    action:action
                },
                function (data) {
                    if (data['msg'] == 'KO'){
                        alert('Invalid action!');
                    }
                }
            );
        });
    });
</script>

easy_comment/templates/easy_comment/comment_list.html
{% load comment_tags %}
{% load mptt_tags %}
{% load staticfiles %}

{% get_comment_list_of post as nodes %}
{% get_comments_user_count post as user_count %}

<div class="container-fluid">
    <div class="comment-count"id="comments">
        <h3>{{ user_count }}人参与，{{ nodes.count }}条评论</h3>
    </div>
    <div class="comment-list">
        {% if nodes.count > 0 %}
            {% recursetree nodes %}
            <div class="row {% if node.is_root_node %}comment-root{% else %}comment-leaf{% endif %}" id="c{{ node.id }}">
                <div class="col-md-1 comment-left">
                    <a class="comment-avatar">
                        <img src="{{ node.user.profile.avatar.url }}"  alt="{{ node.user_name }}头像">
                    </a>
                </div>
                <div class="col-md-11 comment-right">
                    <span class="comment-user"><strong>
                        <a href="{% url 'main_article:userRead' node.user.profile.id %}">
                        {% if node.user_name %}
                        {{node.user_name}}
                        {% else %}
                        {{node.user.username}}
                        {% endif %}
                        </a>
                    </strong></span>
                    {% if not node.is_root_node %}
                    <span class="glyphicon glyphicon-share-alt"></span>
                    <span class="comment-reply-to">@
                    {% if node.parent.user_name %}
                    {{node.parent.user_name}}
                    {% else %}
                    {{node.parent.user.username}}
                    {% endif %}
                    </span>
                    {% endif %}
                    <span class="comment-time pull-right">{{ node.submit_date|timesince }}前</span>
                    <div class="comment-content">
                        <p>{{ node.content|safe }}</p>
                    </div>
                    {% get_like_action request.user node as action %}
                    {% get_like_count node as like_num %}
                    {% get_dislike_count node as dislike_num %}
                    <a class="like {% if not request.user.is_authenticated %}no-login{% endif %}" id="like-{{ node.id }}" data-id="{{ node.id }}" data-action="{% if action == 1 %}cancel-like{% else %}like{% endif %}" href="javascript:void(0);">
                        <span class="glyphicon glyphicon-thumbs-up {% if action == 1 %}red-finger{% endif %}"></span><span class="like-total">{{ like_num }}</span></a>
                    <a class="like {% if not request.user.is_authenticated %}no-login{% endif %}" id="dislike-{{ node.id }}" data-id="{{ node.id }}" data-action="{% if action == -1 %}cancel-dislike{% else %}dislike{% endif %}" href="javascript:void(0);">
                        <span class="glyphicon glyphicon-thumbs-down {% if action == -1  %}red-finger{% endif %}"></span><span class="dislike-total">{{ dislike_num }}</span></a>
                    <a class="comment-reply {% if not request.user.is_authenticated %}no-login{% endif %}" 
                    	data-name="@
                    	{% if node.user_name %}
                        {{node.user_name}}
                        {% else %}
                        {{node.user.username}}
                        {% endif %}" 
                        id="a-{{ node.id }}" href="#cmt-form">
                        回复
                    </a>
                </div>
            </div>
            <div class="comment-children {% if node.is_root_node %}first-generation{% endif %}">
                {% if not node.is_leaf_node %}
                    {{ children }}
                {% endif %}
            </div>
            {% endrecursetree %}
        {% else %}
            <div class="jumbotron">
                <h4>暂无评论，来抢沙发</h4>
            </div>
        {% endif %}
    </div>
</div>

easy_comment/templates/easy_comment/test_index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'easy_comment/css/comment.css' %}">
    <script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
    <script src="http://libs.baidu.com/jquery/2.1.4/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'easy_comment/css/prism.css' %}">
</head>
<body>
    <div class="container">
        <div class="col-md-8 main">
            <h3>{{ message }}</h3>
            {% block content %}
            {% endblock content %}
        </div>
        <div class="col-md-4 side"></div>
    </div>
</body>
</html>